### ISSUE TITLE
Feature - more options to connect 

### ISSUE THREAD

**Issue by a8775** [lawrencekgrant/vscode-cql#2]
Please expose more or all options available when connecting to cassandra: 
http://docs.datastax.com/en/drivers/nodejs/3.0/global.html#ClientOptions

Thanks for your extension it's briliant :)

**Comment by lawrencekgrant** [comment]
I will certainly add this. I am just deciding how if I should let the user define a generic object or not. It seems like it would be superfluous to expose the options individually.

**Comment by lawrencekgrant** [comment]
Also, thanks for the support! It definitely helps me stay focused.
